using System;
using UnityEngine;

namespace HitOrMiss.Pps
{
    /// <summary>
    /// Defines a single PPS trial: looming-pair settings + optional vibrotactile event.
    /// Generated by <see cref="PpsTrialGenerator"/> from <see cref="PpsTaskAsset"/>.
    /// </summary>
    [Serializable]
    public struct PpsTrialDefinition
    {
        [Tooltip("Unique trial identifier (e.g. B1_T07)")]
        public string trialId;

        [Tooltip("Block index (0 = first block; practice uses -1)")]
        public int blockIndex;

        [Tooltip("True if this trial is part of the practice phase")]
        public bool isPractice;

        [Header("Factors")]
        public PpsModality modality;
        public PpsSpeed speed;
        public PpsWidth width;

        [Tooltip("Distance stage at which the vibrotactile event fires. None when modality == VisualOnly.")]
        public DistanceStage vibrationStage;

        /// <summary>
        /// Visual-only trials are passive viewing. Everything else expects a response
        /// time-locked to the vibration event.
        /// </summary>
        public bool RequiresResponse => modality != PpsModality.VisualOnly;

        public static PpsTrialDefinition CreateVisualOnly(int blockIndex, PpsSpeed speed, PpsWidth width, bool isPractice = false)
            => new()
            {
                blockIndex = blockIndex,
                isPractice = isPractice,
                modality = PpsModality.VisualOnly,
                speed = speed,
                width = width,
                vibrationStage = DistanceStage.None,
            };

        /// <summary>
        /// Tactile-only trial. <paramref name="speed"/> determines the matched timing window
        /// (i.e. the moment the vibration fires is computed from the same curve a VT trial
        /// of this speed would use to cross <paramref name="stage"/>). <paramref name="width"/>
        /// carries no visual meaning here but is logged so T and VT trials share a schema.
        /// </summary>
        public static PpsTrialDefinition CreateTactileOnly(int blockIndex, PpsSpeed speed, PpsWidth width, DistanceStage stage, bool isPractice = false)
            => new()
            {
                blockIndex = blockIndex,
                isPractice = isPractice,
                modality = PpsModality.TactileOnly,
                speed = speed,
                width = width,
                vibrationStage = stage,
            };

        public static PpsTrialDefinition CreateBoth(int blockIndex, PpsSpeed speed, PpsWidth width, DistanceStage stage, bool isPractice = false)
            => new()
            {
                blockIndex = blockIndex,
                isPractice = isPractice,
                modality = PpsModality.Both,
                speed = speed,
                width = width,
                vibrationStage = stage,
            };
    }
}
